export * from './AccountType/AccountType';
export * from './auth/register/register';
export * from './Bank/Bank';
export * from './Department/Department';
export * from './menuCircular/menuCircular.interface';
export * from './Person/Person';
export * from './Role/Role';
export * from './sideBar/sideBar';
export * from './Vacation/vacation.interface';
